name: 'release-comment-issues-gh-action'
description: 'A Github Action to comment on related issues when a release is published.'
inputs:
  github_token:
    required: true
    description: 'a github access token'
  version:
    required: true
    description: 'Which version was released'
  changelog_pr_mode:
    required: false
    default: ''
    description: 'By default, this action expects markdown links to PRs in the changelog. You can opt to just look for different matches. Default is empty, other allowed values: SIMPLE_ROUND_BRACKETS'
runs:
  using: 'node20'
  main: 'dist/index.js'
